enum EventType {
    STORM = "STORM",
    FIRE = "FIRE",
    STRONG_WIND="STRONG_WIND",
    EARTHQUAKE = "EARTHQUAKE",
    FLOOD = "FLOOD",
    BIBLICAL_FLOOD = "BIBLICAL_FLOOD",
    WE_NEED_NOAH = "WE_NEED_NOAH",
    HAIL = "HAIL",
    VANDALISM="VANDALISM",
    ELECTRIC_SHOCK = "ELECTRIC_SHOCK",
    MECHANICAL_FAILURE = "MECHANICAL_FAILURE",
    STRUCTURAL_FAILURE = "STRUCTURAL_FAILURE",
}
