FROM node:20-alpine3.19

ARG UID
ARG GID
ARG APPUSR
ARG APPGRP
ARG HOME_DIR
ARG HOME_PROJECT_DIR

COPY ./utils/lib/bash/pre-build-image-alpine.sh /tmp/pre-build-image-alpine.sh
RUN apk add bash && \
    bash /tmp/pre-build-image-alpine.sh

# USER ${APPUSR}
